AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Wodify Notify Template.  Scrape website

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Parameters:
  NotificationSMS:
    Type: String

Resources:
  WodifyNotifyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: wodify_notify/
      Handler: app.lambda_handler
      Runtime: python3.7
      Role: !GetAtt [ LambdaExecutionRole, Arn ]
      Environment:
        Variables:
          PHONE_NUMBERS: !Ref NotificationSMS
      Events:
        CheckWebsiteScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(1 9 ? * SUN-FRI *)

  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        -
          PolicyName: "AdminAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "*"
                Resource: "*"


Outputs:
  WodifyNotifyFunction:
    Description: "Wodify Notify Lambda Function ARN"
    Value: !GetAtt WodifyNotifyFunction.Arn

